version: "3"
services:
  nginx:
    container_name: nginx_container
    build: ./nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../QSIS:/code
      - ./nginx/log:/var/log/nginx
    depends_on:
      - web

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports: 
      - "9090:9090"
    depends_on:
      - web
      - nginx
    # networks:
    #   default:
    #   name: normal-oj_default
    #   external: true

  web:
    container_name: "Django3-Vue"
    build: .
    init: true
    env_file:
      - .env
    # command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && uwsgi --ini  uwsgi.ini"
    volumes:
      - .:/code
      - /mnt/RESIS:/data


# networks:
#   default:
#     name: normal-oj_default
#     external: true